mysql: mysql+pymysql://root:123456@127.0.0.1/data_copilot

ai:
  tries: 3
  retries: 2
  concurrent: 3

llm:
  model: qwen1.5-110b-chat
  url: "https://open.bigmodel.cn/api/paas/v4/"

# qwen1.5-72b-chat   qwen1.5-110b-chat
# qwen-turbo  qwen-plus   qwen-max   qwen-long


server_port: 8087
